apiVersion: v1
kind: Service
metadata:
  name: ds-cc-athena-api-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ds-cc-athena-api-app # defines what pod(s) to send traffic to (pods w/this label will get traffic)
